DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS v_games;
DROP TABLE IF EXISTS music;


CREATE TABLE user(
  user_id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE movies(
  movie_id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT UNIQUE NOT NULL,
  series BOOLEAN DEFAULT FALSE,
  bluray BOOLEAN DEFAULT FALSE
);

CREATE TABLE v_games(
  v_game_id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT UNIQUE NOT NULL,
  series BOOLEAN DEFAULT FALSE,
  system TEXT NOT NULL
);

CREATE TABLE music(
  music_id INTEGER PRIMARY KEY AUTOINCREMENT,
  album TEXT UNIQUE NOT NULL,
  artist TEXT NOT NULL
);
